# This is a basic workflow to help you get started with Actions

name: pullRequestMain

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build docker containers
        run: docker-compose build 
      
      - name: run docker containers
        run: docker-compose up -d
      
      - name: run npm install
        run: |
          cd api
          npm ci
          
      - name: run tests
        run: |
          cd api
          npm run test

